//
// Created by l1nkkk on 2023/3/21.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: taikouGraph.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RpcStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code uint32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  *string `protobuf:"bytes,2,opt,name=msg,proto3,oneof" json:"msg,omitempty"`
}

func (x *RpcStatus) Reset() {
	*x = RpcStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taikouGraph_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcStatus) ProtoMessage() {}

func (x *RpcStatus) ProtoReflect() protoreflect.Message {
	mi := &file_taikouGraph_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcStatus.ProtoReflect.Descriptor instead.
func (*RpcStatus) Descriptor() ([]byte, []int) {
	return file_taikouGraph_proto_rawDescGZIP(), []int{0}
}

func (x *RpcStatus) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RpcStatus) GetMsg() string {
	if x != nil && x.Msg != nil {
		return *x.Msg
	}
	return ""
}

type RpcVertex struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TagID    uint32  `protobuf:"varint,1,opt,name=tagID,proto3" json:"tagID,omitempty"`
	TagStr   *string `protobuf:"bytes,2,opt,name=tagStr,proto3,oneof" json:"tagStr,omitempty"`
	Vid      uint64  `protobuf:"varint,3,opt,name=vid,proto3" json:"vid,omitempty"`
	Property string  `protobuf:"bytes,4,opt,name=property,proto3" json:"property,omitempty"`
}

func (x *RpcVertex) Reset() {
	*x = RpcVertex{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taikouGraph_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcVertex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcVertex) ProtoMessage() {}

func (x *RpcVertex) ProtoReflect() protoreflect.Message {
	mi := &file_taikouGraph_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcVertex.ProtoReflect.Descriptor instead.
func (*RpcVertex) Descriptor() ([]byte, []int) {
	return file_taikouGraph_proto_rawDescGZIP(), []int{1}
}

func (x *RpcVertex) GetTagID() uint32 {
	if x != nil {
		return x.TagID
	}
	return 0
}

func (x *RpcVertex) GetTagStr() string {
	if x != nil && x.TagStr != nil {
		return *x.TagStr
	}
	return ""
}

func (x *RpcVertex) GetVid() uint64 {
	if x != nil {
		return x.Vid
	}
	return 0
}

func (x *RpcVertex) GetProperty() string {
	if x != nil {
		return x.Property
	}
	return ""
}

type RpcEdge struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TagID       uint32  `protobuf:"varint,1,opt,name=tagID,proto3" json:"tagID,omitempty"`
	TagStr      *string `protobuf:"bytes,2,opt,name=tagStr,proto3,oneof" json:"tagStr,omitempty"`
	Vid         uint64  `protobuf:"varint,3,opt,name=vid,proto3" json:"vid,omitempty"`
	EdgeTypeID  uint32  `protobuf:"varint,4,opt,name=edgeTypeID,proto3" json:"edgeTypeID,omitempty"`
	EdgeTypeStr *string `protobuf:"bytes,5,opt,name=edgeTypeStr,proto3,oneof" json:"edgeTypeStr,omitempty"`
	Direction   string  `protobuf:"bytes,6,opt,name=direction,proto3" json:"direction,omitempty"`
	PeerTagID   uint32  `protobuf:"varint,7,opt,name=peerTagID,proto3" json:"peerTagID,omitempty"`
	PeerTagStr  *string `protobuf:"bytes,8,opt,name=peerTagStr,proto3,oneof" json:"peerTagStr,omitempty"`
	PeerVid     uint64  `protobuf:"varint,9,opt,name=peerVid,proto3" json:"peerVid,omitempty"`
	Rank        uint64  `protobuf:"varint,10,opt,name=rank,proto3" json:"rank,omitempty"`
	Property    string  `protobuf:"bytes,11,opt,name=property,proto3" json:"property,omitempty"`
}

func (x *RpcEdge) Reset() {
	*x = RpcEdge{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taikouGraph_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcEdge) ProtoMessage() {}

func (x *RpcEdge) ProtoReflect() protoreflect.Message {
	mi := &file_taikouGraph_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcEdge.ProtoReflect.Descriptor instead.
func (*RpcEdge) Descriptor() ([]byte, []int) {
	return file_taikouGraph_proto_rawDescGZIP(), []int{2}
}

func (x *RpcEdge) GetTagID() uint32 {
	if x != nil {
		return x.TagID
	}
	return 0
}

func (x *RpcEdge) GetTagStr() string {
	if x != nil && x.TagStr != nil {
		return *x.TagStr
	}
	return ""
}

func (x *RpcEdge) GetVid() uint64 {
	if x != nil {
		return x.Vid
	}
	return 0
}

func (x *RpcEdge) GetEdgeTypeID() uint32 {
	if x != nil {
		return x.EdgeTypeID
	}
	return 0
}

func (x *RpcEdge) GetEdgeTypeStr() string {
	if x != nil && x.EdgeTypeStr != nil {
		return *x.EdgeTypeStr
	}
	return ""
}

func (x *RpcEdge) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *RpcEdge) GetPeerTagID() uint32 {
	if x != nil {
		return x.PeerTagID
	}
	return 0
}

func (x *RpcEdge) GetPeerTagStr() string {
	if x != nil && x.PeerTagStr != nil {
		return *x.PeerTagStr
	}
	return ""
}

func (x *RpcEdge) GetPeerVid() uint64 {
	if x != nil {
		return x.PeerVid
	}
	return 0
}

func (x *RpcEdge) GetRank() uint64 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *RpcEdge) GetProperty() string {
	if x != nil {
		return x.Property
	}
	return ""
}

type RpcSubGraph struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ver     *RpcVertex `protobuf:"bytes,1,opt,name=ver,proto3" json:"ver,omitempty"`
	InEdge  []*RpcEdge `protobuf:"bytes,2,rep,name=inEdge,proto3" json:"inEdge,omitempty"`
	OutEdge []*RpcEdge `protobuf:"bytes,3,rep,name=outEdge,proto3" json:"outEdge,omitempty"`
}

func (x *RpcSubGraph) Reset() {
	*x = RpcSubGraph{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taikouGraph_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcSubGraph) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcSubGraph) ProtoMessage() {}

func (x *RpcSubGraph) ProtoReflect() protoreflect.Message {
	mi := &file_taikouGraph_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcSubGraph.ProtoReflect.Descriptor instead.
func (*RpcSubGraph) Descriptor() ([]byte, []int) {
	return file_taikouGraph_proto_rawDescGZIP(), []int{3}
}

func (x *RpcSubGraph) GetVer() *RpcVertex {
	if x != nil {
		return x.Ver
	}
	return nil
}

func (x *RpcSubGraph) GetInEdge() []*RpcEdge {
	if x != nil {
		return x.InEdge
	}
	return nil
}

func (x *RpcSubGraph) GetOutEdge() []*RpcEdge {
	if x != nil {
		return x.OutEdge
	}
	return nil
}

type PingReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Treat string `protobuf:"bytes,1,opt,name=treat,proto3" json:"treat,omitempty"`
}

func (x *PingReq) Reset() {
	*x = PingReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taikouGraph_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReq) ProtoMessage() {}

func (x *PingReq) ProtoReflect() protoreflect.Message {
	mi := &file_taikouGraph_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReq.ProtoReflect.Descriptor instead.
func (*PingReq) Descriptor() ([]byte, []int) {
	return file_taikouGraph_proto_rawDescGZIP(), []int{4}
}

func (x *PingReq) GetTreat() string {
	if x != nil {
		return x.Treat
	}
	return ""
}

type PingResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	S   *RpcStatus `protobuf:"bytes,1,opt,name=s,proto3" json:"s,omitempty"`
	Msg string     `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *PingResp) Reset() {
	*x = PingResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taikouGraph_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResp) ProtoMessage() {}

func (x *PingResp) ProtoReflect() protoreflect.Message {
	mi := &file_taikouGraph_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResp.ProtoReflect.Descriptor instead.
func (*PingResp) Descriptor() ([]byte, []int) {
	return file_taikouGraph_proto_rawDescGZIP(), []int{5}
}

func (x *PingResp) GetS() *RpcStatus {
	if x != nil {
		return x.S
	}
	return nil
}

func (x *PingResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type GetSingleVertexReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tag      *string `protobuf:"bytes,1,opt,name=tag,proto3,oneof" json:"tag,omitempty"`
	PropType *string `protobuf:"bytes,2,opt,name=propType,proto3,oneof" json:"propType,omitempty"`
	KeyWord  *string `protobuf:"bytes,3,opt,name=keyWord,proto3,oneof" json:"keyWord,omitempty"`
}

func (x *GetSingleVertexReq) Reset() {
	*x = GetSingleVertexReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taikouGraph_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSingleVertexReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSingleVertexReq) ProtoMessage() {}

func (x *GetSingleVertexReq) ProtoReflect() protoreflect.Message {
	mi := &file_taikouGraph_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSingleVertexReq.ProtoReflect.Descriptor instead.
func (*GetSingleVertexReq) Descriptor() ([]byte, []int) {
	return file_taikouGraph_proto_rawDescGZIP(), []int{6}
}

func (x *GetSingleVertexReq) GetTag() string {
	if x != nil && x.Tag != nil {
		return *x.Tag
	}
	return ""
}

func (x *GetSingleVertexReq) GetPropType() string {
	if x != nil && x.PropType != nil {
		return *x.PropType
	}
	return ""
}

func (x *GetSingleVertexReq) GetKeyWord() string {
	if x != nil && x.KeyWord != nil {
		return *x.KeyWord
	}
	return ""
}

type GetSingleVertexResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	S   *RpcStatus `protobuf:"bytes,1,opt,name=s,proto3" json:"s,omitempty"`
	Ver *RpcVertex `protobuf:"bytes,2,opt,name=ver,proto3,oneof" json:"ver,omitempty"`
}

func (x *GetSingleVertexResp) Reset() {
	*x = GetSingleVertexResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taikouGraph_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSingleVertexResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSingleVertexResp) ProtoMessage() {}

func (x *GetSingleVertexResp) ProtoReflect() protoreflect.Message {
	mi := &file_taikouGraph_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSingleVertexResp.ProtoReflect.Descriptor instead.
func (*GetSingleVertexResp) Descriptor() ([]byte, []int) {
	return file_taikouGraph_proto_rawDescGZIP(), []int{7}
}

func (x *GetSingleVertexResp) GetS() *RpcStatus {
	if x != nil {
		return x.S
	}
	return nil
}

func (x *GetSingleVertexResp) GetVer() *RpcVertex {
	if x != nil {
		return x.Ver
	}
	return nil
}

type GetSubGraphReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TagID uint32 `protobuf:"varint,1,opt,name=tagID,proto3" json:"tagID,omitempty"`
	Vid   uint64 `protobuf:"varint,2,opt,name=vid,proto3" json:"vid,omitempty"`
}

func (x *GetSubGraphReq) Reset() {
	*x = GetSubGraphReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taikouGraph_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSubGraphReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubGraphReq) ProtoMessage() {}

func (x *GetSubGraphReq) ProtoReflect() protoreflect.Message {
	mi := &file_taikouGraph_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubGraphReq.ProtoReflect.Descriptor instead.
func (*GetSubGraphReq) Descriptor() ([]byte, []int) {
	return file_taikouGraph_proto_rawDescGZIP(), []int{8}
}

func (x *GetSubGraphReq) GetTagID() uint32 {
	if x != nil {
		return x.TagID
	}
	return 0
}

func (x *GetSubGraphReq) GetVid() uint64 {
	if x != nil {
		return x.Vid
	}
	return 0
}

type GetSubGraphResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	S  *RpcStatus   `protobuf:"bytes,1,opt,name=s,proto3" json:"s,omitempty"`
	Sg *RpcSubGraph `protobuf:"bytes,2,opt,name=sg,proto3,oneof" json:"sg,omitempty"`
}

func (x *GetSubGraphResp) Reset() {
	*x = GetSubGraphResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taikouGraph_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSubGraphResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubGraphResp) ProtoMessage() {}

func (x *GetSubGraphResp) ProtoReflect() protoreflect.Message {
	mi := &file_taikouGraph_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubGraphResp.ProtoReflect.Descriptor instead.
func (*GetSubGraphResp) Descriptor() ([]byte, []int) {
	return file_taikouGraph_proto_rawDescGZIP(), []int{9}
}

func (x *GetSubGraphResp) GetS() *RpcStatus {
	if x != nil {
		return x.S
	}
	return nil
}

func (x *GetSubGraphResp) GetSg() *RpcSubGraph {
	if x != nil {
		return x.Sg
	}
	return nil
}

type GetEdgeListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TagID uint32 `protobuf:"varint,1,opt,name=tagID,proto3" json:"tagID,omitempty"`
	Vid   uint64 `protobuf:"varint,2,opt,name=vid,proto3" json:"vid,omitempty"`
}

func (x *GetEdgeListReq) Reset() {
	*x = GetEdgeListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taikouGraph_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEdgeListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEdgeListReq) ProtoMessage() {}

func (x *GetEdgeListReq) ProtoReflect() protoreflect.Message {
	mi := &file_taikouGraph_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEdgeListReq.ProtoReflect.Descriptor instead.
func (*GetEdgeListReq) Descriptor() ([]byte, []int) {
	return file_taikouGraph_proto_rawDescGZIP(), []int{10}
}

func (x *GetEdgeListReq) GetTagID() uint32 {
	if x != nil {
		return x.TagID
	}
	return 0
}

func (x *GetEdgeListReq) GetVid() uint64 {
	if x != nil {
		return x.Vid
	}
	return 0
}

type GetEdgeListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	S        *RpcStatus `protobuf:"bytes,1,opt,name=s,proto3" json:"s,omitempty"`
	EdgeList []*RpcEdge `protobuf:"bytes,2,rep,name=edgeList,proto3" json:"edgeList,omitempty"`
}

func (x *GetEdgeListResp) Reset() {
	*x = GetEdgeListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taikouGraph_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEdgeListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEdgeListResp) ProtoMessage() {}

func (x *GetEdgeListResp) ProtoReflect() protoreflect.Message {
	mi := &file_taikouGraph_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEdgeListResp.ProtoReflect.Descriptor instead.
func (*GetEdgeListResp) Descriptor() ([]byte, []int) {
	return file_taikouGraph_proto_rawDescGZIP(), []int{11}
}

func (x *GetEdgeListResp) GetS() *RpcStatus {
	if x != nil {
		return x.S
	}
	return nil
}

func (x *GetEdgeListResp) GetEdgeList() []*RpcEdge {
	if x != nil {
		return x.EdgeList
	}
	return nil
}

// write
type WriteVertex struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tag        string `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	UniqueName string `protobuf:"bytes,2,opt,name=uniqueName,proto3" json:"uniqueName,omitempty"`
	Property   string `protobuf:"bytes,3,opt,name=property,proto3" json:"property,omitempty"`
}

func (x *WriteVertex) Reset() {
	*x = WriteVertex{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taikouGraph_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteVertex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteVertex) ProtoMessage() {}

func (x *WriteVertex) ProtoReflect() protoreflect.Message {
	mi := &file_taikouGraph_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteVertex.ProtoReflect.Descriptor instead.
func (*WriteVertex) Descriptor() ([]byte, []int) {
	return file_taikouGraph_proto_rawDescGZIP(), []int{12}
}

func (x *WriteVertex) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *WriteVertex) GetUniqueName() string {
	if x != nil {
		return x.UniqueName
	}
	return ""
}

func (x *WriteVertex) GetProperty() string {
	if x != nil {
		return x.Property
	}
	return ""
}

type WriteEdge struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VertexTag      string `protobuf:"bytes,1,opt,name=vertexTag,proto3" json:"vertexTag,omitempty"`
	VertexName     string `protobuf:"bytes,2,opt,name=vertexName,proto3" json:"vertexName,omitempty"`
	Direction      uint32 `protobuf:"varint,3,opt,name=direction,proto3" json:"direction,omitempty"`
	EdgeType       string `protobuf:"bytes,4,opt,name=edgeType,proto3" json:"edgeType,omitempty"`
	VertexTagPeer  string `protobuf:"bytes,5,opt,name=vertexTagPeer,proto3" json:"vertexTagPeer,omitempty"`
	VertexNamePeer string `protobuf:"bytes,6,opt,name=vertexNamePeer,proto3" json:"vertexNamePeer,omitempty"`
	Props          string `protobuf:"bytes,7,opt,name=props,proto3" json:"props,omitempty"`
}

func (x *WriteEdge) Reset() {
	*x = WriteEdge{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taikouGraph_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteEdge) ProtoMessage() {}

func (x *WriteEdge) ProtoReflect() protoreflect.Message {
	mi := &file_taikouGraph_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteEdge.ProtoReflect.Descriptor instead.
func (*WriteEdge) Descriptor() ([]byte, []int) {
	return file_taikouGraph_proto_rawDescGZIP(), []int{13}
}

func (x *WriteEdge) GetVertexTag() string {
	if x != nil {
		return x.VertexTag
	}
	return ""
}

func (x *WriteEdge) GetVertexName() string {
	if x != nil {
		return x.VertexName
	}
	return ""
}

func (x *WriteEdge) GetDirection() uint32 {
	if x != nil {
		return x.Direction
	}
	return 0
}

func (x *WriteEdge) GetEdgeType() string {
	if x != nil {
		return x.EdgeType
	}
	return ""
}

func (x *WriteEdge) GetVertexTagPeer() string {
	if x != nil {
		return x.VertexTagPeer
	}
	return ""
}

func (x *WriteEdge) GetVertexNamePeer() string {
	if x != nil {
		return x.VertexNamePeer
	}
	return ""
}

func (x *WriteEdge) GetProps() string {
	if x != nil {
		return x.Props
	}
	return ""
}

type CreateKGReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KgName string `protobuf:"bytes,1,opt,name=kgName,proto3" json:"kgName,omitempty"`
	Meta   string `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
}

func (x *CreateKGReq) Reset() {
	*x = CreateKGReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taikouGraph_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateKGReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKGReq) ProtoMessage() {}

func (x *CreateKGReq) ProtoReflect() protoreflect.Message {
	mi := &file_taikouGraph_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKGReq.ProtoReflect.Descriptor instead.
func (*CreateKGReq) Descriptor() ([]byte, []int) {
	return file_taikouGraph_proto_rawDescGZIP(), []int{14}
}

func (x *CreateKGReq) GetKgName() string {
	if x != nil {
		return x.KgName
	}
	return ""
}

func (x *CreateKGReq) GetMeta() string {
	if x != nil {
		return x.Meta
	}
	return ""
}

type CreateKGResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	S *RpcStatus `protobuf:"bytes,1,opt,name=s,proto3" json:"s,omitempty"`
}

func (x *CreateKGResp) Reset() {
	*x = CreateKGResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taikouGraph_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateKGResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKGResp) ProtoMessage() {}

func (x *CreateKGResp) ProtoReflect() protoreflect.Message {
	mi := &file_taikouGraph_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKGResp.ProtoReflect.Descriptor instead.
func (*CreateKGResp) Descriptor() ([]byte, []int) {
	return file_taikouGraph_proto_rawDescGZIP(), []int{15}
}

func (x *CreateKGResp) GetS() *RpcStatus {
	if x != nil {
		return x.S
	}
	return nil
}

type PutVertexListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VertexList []*WriteVertex `protobuf:"bytes,1,rep,name=vertexList,proto3" json:"vertexList,omitempty"`
}

func (x *PutVertexListReq) Reset() {
	*x = PutVertexListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taikouGraph_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutVertexListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutVertexListReq) ProtoMessage() {}

func (x *PutVertexListReq) ProtoReflect() protoreflect.Message {
	mi := &file_taikouGraph_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutVertexListReq.ProtoReflect.Descriptor instead.
func (*PutVertexListReq) Descriptor() ([]byte, []int) {
	return file_taikouGraph_proto_rawDescGZIP(), []int{16}
}

func (x *PutVertexListReq) GetVertexList() []*WriteVertex {
	if x != nil {
		return x.VertexList
	}
	return nil
}

type PutVertexListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	S *RpcStatus `protobuf:"bytes,1,opt,name=s,proto3" json:"s,omitempty"`
}

func (x *PutVertexListResp) Reset() {
	*x = PutVertexListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taikouGraph_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutVertexListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutVertexListResp) ProtoMessage() {}

func (x *PutVertexListResp) ProtoReflect() protoreflect.Message {
	mi := &file_taikouGraph_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutVertexListResp.ProtoReflect.Descriptor instead.
func (*PutVertexListResp) Descriptor() ([]byte, []int) {
	return file_taikouGraph_proto_rawDescGZIP(), []int{17}
}

func (x *PutVertexListResp) GetS() *RpcStatus {
	if x != nil {
		return x.S
	}
	return nil
}

type PutEdgeListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EdgeList []*WriteEdge `protobuf:"bytes,1,rep,name=edgeList,proto3" json:"edgeList,omitempty"`
}

func (x *PutEdgeListReq) Reset() {
	*x = PutEdgeListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taikouGraph_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutEdgeListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutEdgeListReq) ProtoMessage() {}

func (x *PutEdgeListReq) ProtoReflect() protoreflect.Message {
	mi := &file_taikouGraph_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutEdgeListReq.ProtoReflect.Descriptor instead.
func (*PutEdgeListReq) Descriptor() ([]byte, []int) {
	return file_taikouGraph_proto_rawDescGZIP(), []int{18}
}

func (x *PutEdgeListReq) GetEdgeList() []*WriteEdge {
	if x != nil {
		return x.EdgeList
	}
	return nil
}

type PutEdgeListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	S *RpcStatus `protobuf:"bytes,1,opt,name=s,proto3" json:"s,omitempty"`
}

func (x *PutEdgeListResp) Reset() {
	*x = PutEdgeListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taikouGraph_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutEdgeListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutEdgeListResp) ProtoMessage() {}

func (x *PutEdgeListResp) ProtoReflect() protoreflect.Message {
	mi := &file_taikouGraph_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutEdgeListResp.ProtoReflect.Descriptor instead.
func (*PutEdgeListResp) Descriptor() ([]byte, []int) {
	return file_taikouGraph_proto_rawDescGZIP(), []int{19}
}

func (x *PutEdgeListResp) GetS() *RpcStatus {
	if x != nil {
		return x.S
	}
	return nil
}

var File_taikouGraph_proto protoreflect.FileDescriptor

var file_taikouGraph_proto_rawDesc = []byte{
	0x0a, 0x11, 0x74, 0x61, 0x69, 0x6b, 0x6f, 0x75, 0x47, 0x72, 0x61, 0x70, 0x68, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x3e, 0x0a, 0x09, 0x52, 0x70, 0x63, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x15, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x00, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x88, 0x01, 0x01, 0x42, 0x06, 0x0a, 0x04, 0x5f,
	0x6d, 0x73, 0x67, 0x22, 0x77, 0x0a, 0x09, 0x52, 0x70, 0x63, 0x56, 0x65, 0x72, 0x74, 0x65, 0x78,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x61, 0x67, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x05, 0x74, 0x61, 0x67, 0x49, 0x44, 0x12, 0x1b, 0x0a, 0x06, 0x74, 0x61, 0x67, 0x53, 0x74, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x74, 0x61, 0x67, 0x53, 0x74, 0x72,
	0x88, 0x01, 0x01, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x03, 0x76, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74,
	0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74,
	0x79, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x74, 0x61, 0x67, 0x53, 0x74, 0x72, 0x22, 0xea, 0x02, 0x0a,
	0x07, 0x52, 0x70, 0x63, 0x45, 0x64, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x61, 0x67, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x74, 0x61, 0x67, 0x49, 0x44, 0x12, 0x1b,
	0x0a, 0x06, 0x74, 0x61, 0x67, 0x53, 0x74, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x06, 0x74, 0x61, 0x67, 0x53, 0x74, 0x72, 0x88, 0x01, 0x01, 0x12, 0x10, 0x0a, 0x03, 0x76,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x76, 0x69, 0x64, 0x12, 0x1e, 0x0a,
	0x0a, 0x65, 0x64, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0a, 0x65, 0x64, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x49, 0x44, 0x12, 0x25, 0x0a,
	0x0b, 0x65, 0x64, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x53, 0x74, 0x72, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x01, 0x52, 0x0b, 0x65, 0x64, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x53, 0x74,
	0x72, 0x88, 0x01, 0x01, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x65, 0x65, 0x72, 0x54, 0x61, 0x67, 0x49, 0x44, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x70, 0x65, 0x65, 0x72, 0x54, 0x61, 0x67, 0x49, 0x44,
	0x12, 0x23, 0x0a, 0x0a, 0x70, 0x65, 0x65, 0x72, 0x54, 0x61, 0x67, 0x53, 0x74, 0x72, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x0a, 0x70, 0x65, 0x65, 0x72, 0x54, 0x61, 0x67, 0x53,
	0x74, 0x72, 0x88, 0x01, 0x01, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x65, 0x65, 0x72, 0x56, 0x69, 0x64,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x70, 0x65, 0x65, 0x72, 0x56, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x72,
	0x61, 0x6e, 0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x18,
	0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x42,
	0x09, 0x0a, 0x07, 0x5f, 0x74, 0x61, 0x67, 0x53, 0x74, 0x72, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x65,
	0x64, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x53, 0x74, 0x72, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x70,
	0x65, 0x65, 0x72, 0x54, 0x61, 0x67, 0x53, 0x74, 0x72, 0x22, 0x71, 0x0a, 0x0b, 0x52, 0x70, 0x63,
	0x53, 0x75, 0x62, 0x47, 0x72, 0x61, 0x70, 0x68, 0x12, 0x1c, 0x0a, 0x03, 0x76, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x52, 0x70, 0x63, 0x56, 0x65, 0x72, 0x74, 0x65,
	0x78, 0x52, 0x03, 0x76, 0x65, 0x72, 0x12, 0x20, 0x0a, 0x06, 0x69, 0x6e, 0x45, 0x64, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x52, 0x70, 0x63, 0x45, 0x64, 0x67, 0x65,
	0x52, 0x06, 0x69, 0x6e, 0x45, 0x64, 0x67, 0x65, 0x12, 0x22, 0x0a, 0x07, 0x6f, 0x75, 0x74, 0x45,
	0x64, 0x67, 0x65, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x52, 0x70, 0x63, 0x45,
	0x64, 0x67, 0x65, 0x52, 0x07, 0x6f, 0x75, 0x74, 0x45, 0x64, 0x67, 0x65, 0x22, 0x1f, 0x0a, 0x07,
	0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x72, 0x65, 0x61, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x72, 0x65, 0x61, 0x74, 0x22, 0x36, 0x0a,
	0x08, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x01, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x52, 0x70, 0x63, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x01, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x8c, 0x01, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x53, 0x69, 0x6e,
	0x67, 0x6c, 0x65, 0x56, 0x65, 0x72, 0x74, 0x65, 0x78, 0x52, 0x65, 0x71, 0x12, 0x15, 0x0a, 0x03,
	0x74, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x03, 0x74, 0x61, 0x67,
	0x88, 0x01, 0x01, 0x12, 0x1f, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x70, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x70, 0x54, 0x79, 0x70,
	0x65, 0x88, 0x01, 0x01, 0x12, 0x1d, 0x0a, 0x07, 0x6b, 0x65, 0x79, 0x57, 0x6f, 0x72, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x07, 0x6b, 0x65, 0x79, 0x57, 0x6f, 0x72, 0x64,
	0x88, 0x01, 0x01, 0x42, 0x06, 0x0a, 0x04, 0x5f, 0x74, 0x61, 0x67, 0x42, 0x0b, 0x0a, 0x09, 0x5f,
	0x70, 0x72, 0x6f, 0x70, 0x54, 0x79, 0x70, 0x65, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x6b, 0x65, 0x79,
	0x57, 0x6f, 0x72, 0x64, 0x22, 0x5a, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x53, 0x69, 0x6e, 0x67, 0x6c,
	0x65, 0x56, 0x65, 0x72, 0x74, 0x65, 0x78, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x01, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x52, 0x70, 0x63, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x01, 0x73, 0x12, 0x21, 0x0a, 0x03, 0x76, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x52, 0x70, 0x63, 0x56, 0x65, 0x72, 0x74, 0x65, 0x78, 0x48, 0x00,
	0x52, 0x03, 0x76, 0x65, 0x72, 0x88, 0x01, 0x01, 0x42, 0x06, 0x0a, 0x04, 0x5f, 0x76, 0x65, 0x72,
	0x22, 0x38, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x53, 0x75, 0x62, 0x47, 0x72, 0x61, 0x70, 0x68, 0x52,
	0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x61, 0x67, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x05, 0x74, 0x61, 0x67, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x76, 0x69, 0x64, 0x22, 0x55, 0x0a, 0x0f, 0x47, 0x65,
	0x74, 0x53, 0x75, 0x62, 0x47, 0x72, 0x61, 0x70, 0x68, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a,
	0x01, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x52, 0x70, 0x63, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x01, 0x73, 0x12, 0x21, 0x0a, 0x02, 0x73, 0x67, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x52, 0x70, 0x63, 0x53, 0x75, 0x62, 0x47, 0x72, 0x61, 0x70,
	0x68, 0x48, 0x00, 0x52, 0x02, 0x73, 0x67, 0x88, 0x01, 0x01, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x73,
	0x67, 0x22, 0x38, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x45, 0x64, 0x67, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x61, 0x67, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x74, 0x61, 0x67, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x76, 0x69, 0x64, 0x22, 0x51, 0x0a, 0x0f, 0x47,
	0x65, 0x74, 0x45, 0x64, 0x67, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18,
	0x0a, 0x01, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x52, 0x70, 0x63, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x01, 0x73, 0x12, 0x24, 0x0a, 0x08, 0x65, 0x64, 0x67, 0x65,
	0x4c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x52, 0x70, 0x63,
	0x45, 0x64, 0x67, 0x65, 0x52, 0x08, 0x65, 0x64, 0x67, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x5b,
	0x0a, 0x0b, 0x57, 0x72, 0x69, 0x74, 0x65, 0x56, 0x65, 0x72, 0x74, 0x65, 0x78, 0x12, 0x10, 0x0a,
	0x03, 0x74, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12,
	0x1e, 0x0a, 0x0a, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x22, 0xe7, 0x01, 0x0a, 0x09,
	0x57, 0x72, 0x69, 0x74, 0x65, 0x45, 0x64, 0x67, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x76, 0x65, 0x72,
	0x74, 0x65, 0x78, 0x54, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x76, 0x65,
	0x72, 0x74, 0x65, 0x78, 0x54, 0x61, 0x67, 0x12, 0x1e, 0x0a, 0x0a, 0x76, 0x65, 0x72, 0x74, 0x65,
	0x78, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x76, 0x65, 0x72,
	0x74, 0x65, 0x78, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x64, 0x69, 0x72, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x64, 0x67, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x64, 0x67, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x24, 0x0a, 0x0d, 0x76, 0x65, 0x72, 0x74, 0x65, 0x78, 0x54, 0x61, 0x67, 0x50, 0x65,
	0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x76, 0x65, 0x72, 0x74, 0x65, 0x78,
	0x54, 0x61, 0x67, 0x50, 0x65, 0x65, 0x72, 0x12, 0x26, 0x0a, 0x0e, 0x76, 0x65, 0x72, 0x74, 0x65,
	0x78, 0x4e, 0x61, 0x6d, 0x65, 0x50, 0x65, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0e, 0x76, 0x65, 0x72, 0x74, 0x65, 0x78, 0x4e, 0x61, 0x6d, 0x65, 0x50, 0x65, 0x65, 0x72, 0x12,
	0x14, 0x0a, 0x05, 0x70, 0x72, 0x6f, 0x70, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x70, 0x72, 0x6f, 0x70, 0x73, 0x22, 0x39, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4b,
	0x47, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x6b, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6b, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x6d, 0x65, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x65, 0x74, 0x61,
	0x22, 0x28, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4b, 0x47, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x18, 0x0a, 0x01, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x52, 0x70,
	0x63, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x01, 0x73, 0x22, 0x40, 0x0a, 0x10, 0x50, 0x75,
	0x74, 0x56, 0x65, 0x72, 0x74, 0x65, 0x78, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x2c,
	0x0a, 0x0a, 0x76, 0x65, 0x72, 0x74, 0x65, 0x78, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x56, 0x65, 0x72, 0x74, 0x65, 0x78,
	0x52, 0x0a, 0x76, 0x65, 0x72, 0x74, 0x65, 0x78, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x2d, 0x0a, 0x11,
	0x50, 0x75, 0x74, 0x56, 0x65, 0x72, 0x74, 0x65, 0x78, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x18, 0x0a, 0x01, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x52,
	0x70, 0x63, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x01, 0x73, 0x22, 0x38, 0x0a, 0x0e, 0x50,
	0x75, 0x74, 0x45, 0x64, 0x67, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x26, 0x0a,
	0x08, 0x65, 0x64, 0x67, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0a, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x45, 0x64, 0x67, 0x65, 0x52, 0x08, 0x65, 0x64, 0x67,
	0x65, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x2b, 0x0a, 0x0f, 0x50, 0x75, 0x74, 0x45, 0x64, 0x67, 0x65,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x01, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x52, 0x70, 0x63, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x01, 0x73, 0x32, 0xe8, 0x02, 0x0a, 0x06, 0x54, 0x61, 0x69, 0x4b, 0x6f, 0x75, 0x12, 0x1d, 0x0a,
	0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x08, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x1a,
	0x09, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x0f,
	0x47, 0x65, 0x74, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x56, 0x65, 0x72, 0x74, 0x65, 0x78, 0x12,
	0x13, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x56, 0x65, 0x72, 0x74, 0x65,
	0x78, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65,
	0x56, 0x65, 0x72, 0x74, 0x65, 0x78, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x0b,
	0x47, 0x65, 0x74, 0x53, 0x75, 0x62, 0x47, 0x72, 0x61, 0x70, 0x68, 0x12, 0x0f, 0x2e, 0x47, 0x65,
	0x74, 0x53, 0x75, 0x62, 0x47, 0x72, 0x61, 0x70, 0x68, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x47,
	0x65, 0x74, 0x53, 0x75, 0x62, 0x47, 0x72, 0x61, 0x70, 0x68, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00,
	0x12, 0x32, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x45, 0x64, 0x67, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x0f, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x64, 0x67, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x1a, 0x10, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x64, 0x67, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x22, 0x00, 0x12, 0x29, 0x0a, 0x08, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4b, 0x47,
	0x12, 0x0c, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4b, 0x47, 0x52, 0x65, 0x71, 0x1a, 0x0d,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4b, 0x47, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12,
	0x38, 0x0a, 0x0d, 0x50, 0x75, 0x74, 0x56, 0x65, 0x72, 0x74, 0x65, 0x78, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x11, 0x2e, 0x50, 0x75, 0x74, 0x56, 0x65, 0x72, 0x74, 0x65, 0x78, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x50, 0x75, 0x74, 0x56, 0x65, 0x72, 0x74, 0x65, 0x78, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x0b, 0x50, 0x75, 0x74,
	0x45, 0x64, 0x67, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x0f, 0x2e, 0x50, 0x75, 0x74, 0x45, 0x64,
	0x67, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x50, 0x75, 0x74, 0x45,
	0x64, 0x67, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x42, 0x0a, 0x5a,
	0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_taikouGraph_proto_rawDescOnce sync.Once
	file_taikouGraph_proto_rawDescData = file_taikouGraph_proto_rawDesc
)

func file_taikouGraph_proto_rawDescGZIP() []byte {
	file_taikouGraph_proto_rawDescOnce.Do(func() {
		file_taikouGraph_proto_rawDescData = protoimpl.X.CompressGZIP(file_taikouGraph_proto_rawDescData)
	})
	return file_taikouGraph_proto_rawDescData
}

var file_taikouGraph_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_taikouGraph_proto_goTypes = []interface{}{
	(*RpcStatus)(nil),           // 0: RpcStatus
	(*RpcVertex)(nil),           // 1: RpcVertex
	(*RpcEdge)(nil),             // 2: RpcEdge
	(*RpcSubGraph)(nil),         // 3: RpcSubGraph
	(*PingReq)(nil),             // 4: PingReq
	(*PingResp)(nil),            // 5: PingResp
	(*GetSingleVertexReq)(nil),  // 6: GetSingleVertexReq
	(*GetSingleVertexResp)(nil), // 7: GetSingleVertexResp
	(*GetSubGraphReq)(nil),      // 8: GetSubGraphReq
	(*GetSubGraphResp)(nil),     // 9: GetSubGraphResp
	(*GetEdgeListReq)(nil),      // 10: GetEdgeListReq
	(*GetEdgeListResp)(nil),     // 11: GetEdgeListResp
	(*WriteVertex)(nil),         // 12: WriteVertex
	(*WriteEdge)(nil),           // 13: WriteEdge
	(*CreateKGReq)(nil),         // 14: CreateKGReq
	(*CreateKGResp)(nil),        // 15: CreateKGResp
	(*PutVertexListReq)(nil),    // 16: PutVertexListReq
	(*PutVertexListResp)(nil),   // 17: PutVertexListResp
	(*PutEdgeListReq)(nil),      // 18: PutEdgeListReq
	(*PutEdgeListResp)(nil),     // 19: PutEdgeListResp
}
var file_taikouGraph_proto_depIdxs = []int32{
	1,  // 0: RpcSubGraph.ver:type_name -> RpcVertex
	2,  // 1: RpcSubGraph.inEdge:type_name -> RpcEdge
	2,  // 2: RpcSubGraph.outEdge:type_name -> RpcEdge
	0,  // 3: PingResp.s:type_name -> RpcStatus
	0,  // 4: GetSingleVertexResp.s:type_name -> RpcStatus
	1,  // 5: GetSingleVertexResp.ver:type_name -> RpcVertex
	0,  // 6: GetSubGraphResp.s:type_name -> RpcStatus
	3,  // 7: GetSubGraphResp.sg:type_name -> RpcSubGraph
	0,  // 8: GetEdgeListResp.s:type_name -> RpcStatus
	2,  // 9: GetEdgeListResp.edgeList:type_name -> RpcEdge
	0,  // 10: CreateKGResp.s:type_name -> RpcStatus
	12, // 11: PutVertexListReq.vertexList:type_name -> WriteVertex
	0,  // 12: PutVertexListResp.s:type_name -> RpcStatus
	13, // 13: PutEdgeListReq.edgeList:type_name -> WriteEdge
	0,  // 14: PutEdgeListResp.s:type_name -> RpcStatus
	4,  // 15: TaiKou.Ping:input_type -> PingReq
	6,  // 16: TaiKou.GetSingleVertex:input_type -> GetSingleVertexReq
	8,  // 17: TaiKou.GetSubGraph:input_type -> GetSubGraphReq
	10, // 18: TaiKou.GetEdgeList:input_type -> GetEdgeListReq
	14, // 19: TaiKou.CreateKG:input_type -> CreateKGReq
	16, // 20: TaiKou.PutVertexList:input_type -> PutVertexListReq
	18, // 21: TaiKou.PutEdgeList:input_type -> PutEdgeListReq
	5,  // 22: TaiKou.Ping:output_type -> PingResp
	7,  // 23: TaiKou.GetSingleVertex:output_type -> GetSingleVertexResp
	9,  // 24: TaiKou.GetSubGraph:output_type -> GetSubGraphResp
	11, // 25: TaiKou.GetEdgeList:output_type -> GetEdgeListResp
	15, // 26: TaiKou.CreateKG:output_type -> CreateKGResp
	17, // 27: TaiKou.PutVertexList:output_type -> PutVertexListResp
	19, // 28: TaiKou.PutEdgeList:output_type -> PutEdgeListResp
	22, // [22:29] is the sub-list for method output_type
	15, // [15:22] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_taikouGraph_proto_init() }
func file_taikouGraph_proto_init() {
	if File_taikouGraph_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_taikouGraph_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taikouGraph_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcVertex); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taikouGraph_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcEdge); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taikouGraph_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcSubGraph); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taikouGraph_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taikouGraph_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taikouGraph_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSingleVertexReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taikouGraph_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSingleVertexResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taikouGraph_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSubGraphReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taikouGraph_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSubGraphResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taikouGraph_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEdgeListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taikouGraph_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEdgeListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taikouGraph_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteVertex); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taikouGraph_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteEdge); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taikouGraph_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateKGReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taikouGraph_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateKGResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taikouGraph_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutVertexListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taikouGraph_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutVertexListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taikouGraph_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutEdgeListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taikouGraph_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutEdgeListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_taikouGraph_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_taikouGraph_proto_msgTypes[1].OneofWrappers = []interface{}{}
	file_taikouGraph_proto_msgTypes[2].OneofWrappers = []interface{}{}
	file_taikouGraph_proto_msgTypes[6].OneofWrappers = []interface{}{}
	file_taikouGraph_proto_msgTypes[7].OneofWrappers = []interface{}{}
	file_taikouGraph_proto_msgTypes[9].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_taikouGraph_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_taikouGraph_proto_goTypes,
		DependencyIndexes: file_taikouGraph_proto_depIdxs,
		MessageInfos:      file_taikouGraph_proto_msgTypes,
	}.Build()
	File_taikouGraph_proto = out.File
	file_taikouGraph_proto_rawDesc = nil
	file_taikouGraph_proto_goTypes = nil
	file_taikouGraph_proto_depIdxs = nil
}
